name: Cypress Tests

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
      
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
        continue-on-error: true
      
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure() || steps.cypress.outcome == 'failure'
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
      
      - name: Create GitHub Issue on Test Failure
        if: failure() || steps.cypress.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = `Échec des tests Cypress - ${new Date().toISOString().split('T')[0]}`;
            const issueBody = `
            ## Rapport d'échec des tests Cypress
            
            ### Informations du workflow
            - Run ID: ${process.env.GITHUB_RUN_ID}
            - Déclenché par: ${process.env.GITHUB_ACTOR}
            - SHA: ${process.env.GITHUB_SHA}
            
            ### Captures d'écran
            Les captures d'écran des tests échoués sont disponibles dans les artefacts de cette exécution.
            [Voir les artefacts](https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['test-failure', 'cypress']
            });